### ISSUE TITLE
failed to import

### ISSUE THREAD

**Issue by wjo1212** [topper-123/freezedata#1]
I like the idea to have this module as helpful tool. but it doesn't work after installation.

>>> import freezedata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wjo1212/fp_book_p36/lib/python3.6/site-packages/freezedata/__init__.py", line 7, in <module>
    __doc__ = open(README).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wjo1212/fp_book_p36/lib/python3.6/site-packages/freezedata/README.rst'

machine: Mac, but should be unrelated to the OS.

better to add UT automatically before releasing.

**Comment by topper-123** [comment]
Fixed. Update to version 2.2.7 and try again now.
